language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

matrix:
  include:
    - php: 7.2
      addons:
        apt:
          packages:
            - libxml2-utils

before_script:
  - composer install --no-interaction

script:
  - xmllint --noout ruleset.xml
